CREATE TABLE NITROGENATED_BASES (
    NITROGENATEDBASE_SYMBOL VARCHAR2(1) NOT NULL,
    NITROGENATEDBASE_NAME VARCHAR2(255) NOT NULL,
    CHEMICAL_FORMULA_ID VARCHAR2(255) NOT NULL
);

ALTER TABLE NITROGENATED_BASES ADD CONSTRAINT nitrogenated_base_id_pk PRIMARY KEY (NITROGENATEDBASE_SYMBOL);
ALTER TABLE NITROGENATED_BASES ADD CONSTRAINT nitrogenatedbases_chemical_formula_id_fk FOREIGN KEY (CHEMICAL_FORMULA_ID) REFERENCES CHEMICAL_FORMULAS(CHEMICAL_FORMULA_ID) ON DELETE CASCADE;

COMMENT ON TABLE NITROGENATED_BASES IS 'Nitrogenated Bases.';

INSERT INTO NITROGENATED_BASES (NITROGENATEDBASE_SYMBOL, NITROGENATEDBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('A', 'Adenina', 'C5H5N5');
INSERT INTO NITROGENATED_BASES (NITROGENATEDBASE_SYMBOL, NITROGENATEDBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('T', 'Timina', 'C5H6N2O2');
INSERT INTO NITROGENATED_BASES (NITROGENATEDBASE_SYMBOL, NITROGENATEDBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('C', 'Citosina', 'C4H5N3O1');
INSERT INTO NITROGENATED_BASES (NITROGENATEDBASE_SYMBOL, NITROGENATEDBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('G', 'Guanina', 'C5H5N5O1');
INSERT INTO NITROGENATED_BASES (NITROGENATEDBASE_SYMBOL, NITROGENATEDBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('U', 'Uracil', 'C4H4N2O2');