CREATE TABLE NITROGENOUS_BASES (
    NITROGENOUSBASE_SYMBOL VARCHAR2(1) NOT NULL,
    NITROGENOUSBASE_NAME VARCHAR2(255) NOT NULL,
    CHEMICAL_FORMULA_ID VARCHAR2(255) NOT NULL
);

ALTER TABLE NITROGENOUS_BASES ADD CONSTRAINT NITROGENOUS_base_id_pk PRIMARY KEY (NITROGENOUSBASE_SYMBOL);
ALTER TABLE NITROGENOUS_BASES ADD CONSTRAINT NITROGENOUSbases_chemical_formula_id_fk FOREIGN KEY (CHEMICAL_FORMULA_ID) REFERENCES CHEMICAL_FORMULAS(CHEMICAL_FORMULA_ID) ON DELETE CASCADE;

COMMENT ON TABLE NITROGENOUS_BASES IS 'NITROGENOUS Bases.';

INSERT INTO NITROGENOUS_BASES (NITROGENOUSBASE_SYMBOL, NITROGENOUSBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('A', 'Adenina', 'C5H5N5');
INSERT INTO NITROGENOUS_BASES (NITROGENOUSBASE_SYMBOL, NITROGENOUSBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('T', 'Timina', 'C5H6N2O2');
INSERT INTO NITROGENOUS_BASES (NITROGENOUSBASE_SYMBOL, NITROGENOUSBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('C', 'Citosina', 'C4H5N3O1');
INSERT INTO NITROGENOUS_BASES (NITROGENOUSBASE_SYMBOL, NITROGENOUSBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('G', 'Guanina', 'C5H5N5O1');
INSERT INTO NITROGENOUS_BASES (NITROGENOUSBASE_SYMBOL, NITROGENOUSBASE_NAME, CHEMICAL_FORMULA_ID) VALUES ('U', 'Uracil', 'C4H4N2O2');
