CREATE TABLE PARTICLES (
    PARTICLE_NAME_ID VARCHAR2(255) NOT NULL
);

ALTER TABLE PARTICLES ADD CONSTRAINT particle_id_pk PRIMARY KEY (PARTICLE_NAME_ID);

COMMENT ON TABLE PARTICLES IS 'Types of nuclear particles.';

INSERT INTO PARTICLES (PARTICLE_NAME_ID) VALUES ('Proton');
INSERT INTO PARTICLES (PARTICLE_NAME_ID) VALUES ('Neutron');
