CREATE TABLE PARTICLES (
    PARTICLE_ID NUMBER(1) GENERATED ALWAYS AS IDENTITY NOT NULL,
    PARTICLE_NAME VARCHAR2(255) NOT NULL,
    UNIT_OF_PARTICLE NUMBER(1) NOT NULL
);

ALTER TABLE PARTICLES ADD CONSTRAINT particle_id_pk PRIMARY KEY (PARTICLE_ID);

COMMENT ON TABLE NEUTRONS_QUARKS IS 'Types of nuclear particles.';

INSERT INTO PARTICLES (PARTICLE_NAME, UNIT_OF_PARTICLE) VALUES ('Proton', 1);
INSERT INTO PARTICLES (PARTICLE_NAME, UNIT_OF_PARTICLE) VALUES ('Neutron', 1);

-- ALTER TABLE PARTICLES DROP CONSTRAINT particle_id_pk; --
-- DROP TABLE PARTICLES; --
