CREATE TABLE ELEMENTS (
    ELEMENT_ID NUMBER(3) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ELEMENT_NAME VARCHAR2(255) NOT NULL,
    ELEMENT_SYMBOL VARCHAR2(2) NOT NULL,
    ELEMENT_ATOMIC_MASS NUMBER NOT NULL,
    ELEMENT_PROTONS NUMBER(3) NOT NULL,
    ELEMENT_NEUTRONS NUMBER(3) NOT NULL
);

COMMENT ON TABLE ELEMENTS IS 'Periodic Table.';

ALTER TABLE ELEMENTS ADD CONSTRAINT element_id_pk PRIMARY KEY (ELEMENT_ID);

INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Hydrogen', 'H', 1.00784, 1, 0);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Helium', 'He', 4.002602, 2, 2);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Lithium', 'Li', 6.941, 3, 4);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Beryllium', 'Be', 9.012182, 4, 5);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Boron', 'B', 10.811, 5, 6);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Carbon', 'C', 12.0107, 6, 6);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Nitrogen', 'N', 14.0067, 7, 7);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Oxygen', 'O', 15.999, 8, 8);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Fluorine', 'F', 18.9984032, 9, 10);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Neon', 'Ne', 20.1797, 10, 10);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Sodium', 'Na', 22.98976928, 11, 12);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Magnesium', 'Mg', 24.305, 12, 12);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Aluminum', 'Al', 26.9815384, 13, 14);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Silicon', 'Si', 28.085, 14, 14);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Phosphorus', 'P', 30.973761998, 15, 16);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Sulfur', 'S', 32.06, 16, 16);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Chlorine', 'Cl', 35.45, 17, 18);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Argon', 'Ar', 39.948, 18, 22);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Potassium', 'K', 39.0983, 19, 20);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Calcium', 'Ca', 40.078, 20, 20);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Scandium', 'Sc', 44.955908, 21, 24);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Titanium', 'Ti', 47.867, 22, 26);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Vanadium', 'V', 50.9415, 23, 28);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Chromium', 'Cr', 51.9961, 24, 28);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Manganese', 'Mn', 54.938044, 25, 30);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Iron', 'Fe', 55.845, 26, 30);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Cobalt', 'Co', 58.933194, 27, 32);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Nickel', 'Ni', 58.6934, 28, 31);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Copper', 'Cu', 63.546, 29, 35);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Zinc', 'Zn', 65.38, 30, 35);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Gallium', 'Ga', 69.723, 31, 39);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Germanium', 'Ge', 72.63, 32, 41);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Arsenic', 'As', 74.921595, 33, 42);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Selenium', 'Se', 78.971, 34, 45);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Bromine', 'Br', 79.904, 35, 45);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Krypton', 'Kr', 83.798, 36, 48);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Rubidium', 'Rb', 85.4678, 37, 48);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Strontium', 'Sr', 87.62, 38, 50);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Yttrium', 'Y', 88.90584, 39, 50);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Zirconium', 'Zr', 91.224, 40, 51);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Niobium', 'Nb', 92.90637, 41, 52);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Molybdenum', 'Mo', 95.95, 42, 54);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Technetium', 'Tc', 98, 43, 55);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Ruthenium', 'Ru', 101.07, 44, 57);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Rhodium', 'Rh', 102.9055, 45, 58);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Palladium', 'Pd', 106.42, 46, 60);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Silver', 'Ag', 107.8682, 47, 61);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Cadmium', 'Cd', 112.414, 48, 64);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Indium', 'In', 114.818, 49, 66);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Tin', 'Sn', 118.71, 50, 69);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Antimony', 'Sb', 121.76, 51, 71);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Tellurium', 'Te', 127.6, 52, 76);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Iodine', 'I', 126.90447, 53, 74);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Xenon', 'Xe', 131.293, 54, 77);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Cesium', 'Cs', 132.90545196, 55, 78);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Barium', 'Ba', 137.327, 56, 81);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Lanthanum', 'La', 138.90547, 57, 82);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Cerium', 'Ce', 140.116, 58, 82);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Praseodymium', 'Pr', 140.90766, 59, 82);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Neodymium', 'Nd', 144.242, 60, 84);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Promethium', 'Pm', 145, 61, 84);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Samarium', 'Sm', 150.36, 62, 88);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Europium', 'Eu', 151.964, 63, 89);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Gadolinium', 'Gd', 157.25, 64, 93);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Terbium', 'Tb', 158.92535, 65, 93);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Dysprosium', 'Dy', 162.5, 66, 97);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Holmium', 'Ho', 164.93033, 67, 98);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Erbium', 'Er', 167.259, 68, 99);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Thulium', 'Tm', 168.93422, 69, 100);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Ytterbium', 'Yb', 173.045, 70, 103);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Lutetium', 'Lu', 174.9668, 71, 104);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Hafnium', 'Hf', 178.49, 72, 106);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Tantalum', 'Ta', 180.94788, 73, 108);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Tungsten', 'W', 183.84, 74, 110);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Rhenium', 'Re', 186.207, 75, 111);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Osmium', 'Os', 190.23, 76, 114);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Iridium', 'Ir', 192.217, 77, 115);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Platinum', 'Pt', 195.084, 78, 117);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Gold', 'Au', 196.966569, 79, 118);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Mercury', 'Hg', 200.592, 80, 121);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Thallium', 'Tl', 204.38, 81, 123);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Lead', 'Pb', 207.2, 82, 125);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Bismuth', 'Bi', 208.9804, 83, 126);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Polonium', 'Po', 209, 84, 125);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Astatine', 'At', 210, 85, 125);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Radon', 'Rn', 222, 86, 136);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Francium', 'Fr', 223, 87, 136);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Radium', 'Ra', 226, 88, 138);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Actinium', 'Ac', 227, 89, 138);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Thorium', 'Th', 232.0377, 90, 142);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Protactinium', 'Pa', 231.03588, 91, 140);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Uranium', 'U', 238.02891, 92, 146);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Neptunium', 'Np', 237, 93, 144);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Plutonium', 'Pu', 244, 94, 150);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Americium', 'Am', 243, 95, 148);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Curium', 'Cm', 247, 96, 151);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Berkelium', 'Bk', 247, 97, 150);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Californium', 'Cf', 251, 98, 153);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Einsteinium', 'Es', 252, 99, 153);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Fermium', 'Fm', 257, 100, 157);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Mendelevium', 'Md', 258, 101, 157);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Nobelium', 'No', 259, 102, 157);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Lawrencium', 'Lr', 262, 103, 159);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Rutherfordium', 'Rf', 267, 104, 163);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Dubnium', 'Db', 270, 105, 163);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Seaborgium', 'Sg', 271, 106, 165);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Bohrium', 'Bh', 270, 107, 163);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Hassium', 'Hs', 277, 108, 169);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Meitnerium', 'Mt', 276, 109, 167);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Darmstadtium', 'Ds', 281, 110, 171);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Roentgenium', 'Rg', 280, 111, 171);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Copernicium', 'Cn', 285, 112, 173);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Nihonium', 'Nh', 284, 113, 171);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Flerovium', 'Fl', 289, 114, 175);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Moscovium', 'Mc', 288, 115, 175);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Livermorium', 'Lv', 293, 116, 177);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Tennessine', 'Ts', 294, 117, 177);
INSERT INTO ELEMENTS (ELEMENT_NAME, ELEMENT_SYMBOL, ELEMENT_ATOMIC_MASS, ELEMENT_PROTONS, ELEMENT_NEUTRONS ) VALUES ('Oganesson', 'Og', 294, 118, 176);

-- ALTER TABLE ELEMENTS DROP CONSTRAINT element_id_pk; --
-- ALTER TABLE ELEMENTS DROP CONSTRAINT particle_id_fk; --
-- DROP TABLE ELEMENTS; --
