CREATE TABLE SUBPARTICLES_PARTICLES (
    SUBPARTICLES_PARTICLE_ID NUMBER(1) GENERATED ALWAYS AS IDENTITY NOT NULL,
    SUBPARTICLE_NAME_ID VARCHAR2(255) NOT NULL,
    PARTICLE_NAME_ID VARCHAR2(255) NOT NULL,
    QUARKS_UP_IN_PARTICLE NUMBER(1),
    QUARKS_DOWN_IN_PARTICLE NUMBER(1)
);

ALTER TABLE SUBPARTICLES_PARTICLES ADD CONSTRAINT subparticles_particle_id_pk PRIMARY KEY (SUBPARTICLES_PARTICLE_ID);
ALTER TABLE SUBPARTICLES_PARTICLES ADD CONSTRAINT subparticle_id_fk FOREIGN KEY (SUBPARTICLE_NAME_ID) REFERENCES SUBPARTICLES(SUBPARTICLE_NAME_ID) ON DELETE CASCADE;
ALTER TABLE SUBPARTICLES_PARTICLES ADD CONSTRAINT particle_id_fk FOREIGN KEY (PARTICLE_NAME_ID) REFERENCES PARTICLES(PARTICLE_NAME_ID) ON DELETE CASCADE;

COMMENT ON TABLE SUBPARTICLES_PARTICLES IS 'Quarks Up and Down are in one proton and one neutron.';

-- Quarks Up are in one proton. --
INSERT INTO SUBPARTICLES_PARTICLES (SUBPARTICLE_NAME_ID, PARTICLE_NAME_ID, QUARKS_UP_IN_PARTICLE, QUARKS_DOWN_IN_PARTICLE) VALUES ('Up', 'Proton', 2, NULL);
-- Quarks Down are in one proton. --
INSERT INTO SUBPARTICLES_PARTICLES (SUBPARTICLE_NAME_ID, PARTICLE_NAME_ID, QUARKS_UP_IN_PARTICLE, QUARKS_DOWN_IN_PARTICLE) VALUES ('Down', 'Proton', NULL, 1);
-- Quarks Down are in one neutron. --
INSERT INTO SUBPARTICLES_PARTICLES (SUBPARTICLE_NAME_ID, PARTICLE_NAME_ID, QUARKS_UP_IN_PARTICLE, QUARKS_DOWN_IN_PARTICLE) VALUES ('Up', 'Neutron', 1, NULL);
-- Quarks Down are in one neutron. --
INSERT INTO SUBPARTICLES_PARTICLES (SUBPARTICLE_NAME_ID, PARTICLE_NAME_ID, QUARKS_UP_IN_PARTICLE, QUARKS_DOWN_IN_PARTICLE) VALUES ('Down', 'Neutron', NULL, 2);
