CREATE TABLE SUBPARTICLES_PARTICLES (
    SUBPARTICLES_PARTICLE_ID NUMBER(1) GENERATED ALWAYS AS IDENTITY NOT NULL,
    SUBPARTICLE_ID NUMBER(2) NOT NULL,
    PARTICLE_ID NUMBER(2) NOT NULL,
    QUARKS_UP_IN_PARTICLE NUMBER(1),
    QUARKS_DOWN_IN_PARTICLE NUMBER(1)  
);

COMMENT ON TABLE SUBPARTICLES_PARTICLES IS 'Quarks Up and Down are in one proton and one neutron.';

ALTER TABLE SUBPARTICLES_PARTICLES ADD CONSTRAINT subparticles_particle_id_pk PRIMARY KEY (SUBPARTICLES_PARTICLE_ID);
ALTER TABLE SUBPARTICLES_PARTICLES ADD CONSTRAINT subparticle_id_fk FOREIGN KEY (SUBPARTICLE_ID) REFERENCES SUBPARTICLES(SUBPARTICLE_ID) ON DELETE CASCADE;
ALTER TABLE SUBPARTICLES_PARTICLES ADD CONSTRAINT particle_id_fk FOREIGN KEY (PARTICLE_ID) REFERENCES PARTICLES(PARTICLE_ID) ON DELETE CASCADE;

-- Quarks Up are in one proton. --
INSERT INTO SUBPARTICLES_PARTICLES (SUBPARTICLE_ID, PARTICLE_ID, QUARKS_UP_IN_PARTICLE, QUARKS_DOWN_IN_PARTICLE) VALUES (1, 1, 2, NULL);
-- Quarks Down are in one proton. --
INSERT INTO SUBPARTICLES_PARTICLES (SUBPARTICLE_ID, PARTICLE_ID, QUARKS_UP_IN_PARTICLE, QUARKS_DOWN_IN_PARTICLE) VALUES (4, 1, NULL, 1);
-- Quarks Down are in one neutron. --
INSERT INTO SUBPARTICLES_PARTICLES (SUBPARTICLE_ID, PARTICLE_ID, QUARKS_UP_IN_PARTICLE, QUARKS_DOWN_IN_PARTICLE) VALUES (1, 2, 1, NULL);
-- Quarks Down are in one neutron. --
INSERT INTO SUBPARTICLES_PARTICLES (SUBPARTICLE_ID, PARTICLE_ID, QUARKS_UP_IN_PARTICLE, QUARKS_DOWN_IN_PARTICLE) VALUES (4, 2, NULL, 2);

-- ALTER TABLE SUBPARTICLES_PARTICLES DROP CONSTRAINT subparticles_particle_id_pk; --
-- ALTER TABLE SUBPARTICLES_PARTICLES DROP CONSTRAINT subparticle_id_fk; --
-- ALTER TABLE SUBPARTICLES_PARTICLES DROP CONSTRAINT particle_id_fk; --
-- DROP TABLE SUBPARTICLES_PARTICLES; --