drop table "ALEXEIBARBERA1"."AMINOACIDS" cascade constraints PURGE;
drop table "ALEXEIBARBERA1"."AMINOACIDS_NITROGENATEDBASES" cascade constraints PURGE;
drop table "ALEXEIBARBERA1"."CHEMICAL_FORMULAS" cascade constraints PURGE;
drop table "ALEXEIBARBERA1"."ELEMENTS" cascade constraints PURGE;
drop table "ALEXEIBARBERA1"."ELEMENTS_CHEMICALFORMULAS" cascade constraints PURGE;
drop table "ALEXEIBARBERA1"."NITROGENATED_BASES" cascade constraints PURGE;
drop table "ALEXEIBARBERA1"."PARTICLES" cascade constraints PURGE;
drop table "ALEXEIBARBERA1"."SUBPARTICLES" cascade constraints PURGE;
drop table "ALEXEIBARBERA1"."SUBPARTICLES_PARTICLES" cascade constraints PURGE;