SET SERVEROUTPUT ON;

-- Ejemplos de uso:

CALL QUARKS_MOLECULE(1, 'He2O4');
CALL QUARKS_MOLECULE(1, 'H2O');
CALL QUARKS_MOLECULE(1, 'c77h120n18o26s');
CALL QUARKS_MOLECULE(1, 'C5H5N5O1');
-- Ejemplos de MAL uso.
CALL QUARKS_MOLECULE(1, '5h5N5O1');
CALL QUARKS_MOLECULE(1, 'XD5N5O1');