SET SERVEROUTPUT ON;

-- Ejemplos de uso:

CALL SUBPARTICLES_NITROGENOUSBASES('AGUCUCAUCUACUCAUCAGACAUGACA');
CALL SUBPARTICLES_NITROGENOUSBASES('uacuacuaguacgucagucagggacaggacacga');
CALL SUBPARTICLES_NITROGENOUSBASES('acugggcgagcaggcgaggca');
CALL SUBPARTICLES_NITROGENOUSBASES('GGCAGCAGGCAGUGCAC');
CALL SUBPARTICLES_NITROGENOUSBASES('UUUUCAUCUACa');
CALL SUBPARTICLES_NITROGENOUSBASES('ACGU');
CALL SUBPARTICLES_NITROGENOUSBASES('aaacgcgcgcggcgcggcauucgaucgua');
CALL SUBPARTICLES_NITROGENOUSBASES('AAAACCCCGUCGUCAGUACGAA');

-- Ejemplos de MAL uso.
CALL SUBPARTICLES_NITROGENOUSBASES('ZXCVTACTGAAT_AGATAGACAGATA');
CALL SUBPARTICLES_NITROGENOUSBASES('ACGTT1234AAT_AGATAGACAGATA');
CALL SUBPARTICLES_NITROGENOUSBASES('ACGTTACTG5ATGAGATAGACAGATA');
CALL SUBPARTICLES_NITROGENOUSBASES('ACGTTACTGAATGAGATAGAC??GATA');
CALL SUBPARTICLES_NITROGENOUSBASES('ACGTTACTGAATGAGATAGACAGATA');
CALL SUBPARTICLES_NITROGENOUSBASES('ACTCTACTAGCTAGCTACA');
CALL SUBPARTICLES_NITROGENOUSBASES('AGUTCAUGCA');
